get:
  summary: Returns a list of users
  responses:
    '200':
      description: A JSON array of user names
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/User.yaml'
