openapi: 3.0.0
info:
  title: Twitter Clone - 2024
  description: API documentation example
  version: 1.0.0
servers:
  - url: 'http://localhost:4000/api/v1'
tags:
  - name: users
    description: Operations about user
paths:
  /users/login:
    get:
      summary: Returns a list of users
      description: Update an existing pet by Id
      operationId: updatePet
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 10
                username:
                  type: string
                  example: theUser
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: James
                email:
                  type: string
                  example: john@email.com
                password:
                  type: string
                  example: '12345'
                phone:
                  type: string
                  example: '12345'
                userStatus:
                  type: integer
                  description: User Status
                  format: int32
                  example: 1
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 10
                    username:
                      type: string
                      example: theUser
                    firstName:
                      type: string
                      example: John
                    lastName:
                      type: string
                      example: James
                    email:
                      type: string
                      example: john@email.com
                    password:
                      type: string
                      example: '12345'
                    phone:
                      type: string
                      example: '12345'
                    userStatus:
                      type: integer
                      description: User Status
                      format: int32
                      example: 1
  /products:
    get:
      summary: Returns a list of users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 10
                    username:
                      type: string
                      example: theUser
                    firstName:
                      type: string
                      example: John
                    lastName:
                      type: string
                      example: James
                    email:
                      type: string
                      example: john@email.com
                    password:
                      type: string
                      example: '12345'
                    phone:
                      type: string
                      example: '12345'
                    userStatus:
                      type: integer
                      description: User Status
                      format: int32
                      example: 1
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
        userStatus:
          type: integer
          description: User Status
          format: int32
          example: 1
